// Rackspace and song selector extension for Gig Performer by @rank13

#include <vector>
#include <string>

// List of panels: the names that appear in the GP UI
std::vector<std::string> panelNames = {"Global Panel"};

// XML for the default included panels
std::vector<std::string> panelXML = { 
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
"<RACKUNIT size=\"10\" style=\"1024\" color=\"ff1b1b1b\" ver=\"4.199999809265137\">"
"  <WIDGET type=\"2\" style=\"1\" x=\"0.5356425702811245\" y=\"0.4913294797687861\""
"          width=\"0.0853413654618474\" height=\"0.9710982658959537\" caption=\"Page Scroll\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.1294117647058824\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"15474\" rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"0.0\""
"          backPlate=\"11\" backPlateVisible=\"0\" invertMIDI=\"0\" displayRange=\"2\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"GPLC_SCROLL\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\""
"          widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\""
"          setDefaultDoubleClickResetValue=\"0.0\" globalAssignedParameterNumber=\"-1\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.4538152610441767\" y=\"0.6271676300578035\""
"          width=\"0.09839357429718876\" height=\"0.4797687861271676\" caption=\"Page Down\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.2168674698795181\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"0.0\""
"          backPlate=\"7\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"GPLC_DOWN\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\""
"          widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\""
"          setDefaultDoubleClickResetValue=\"0.0\" globalAssignedParameterNumber=\"-1\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\" btnRadioGroupIndex=\"0\""
"          btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.356425702811245\" y=\"0.6271676300578035\""
"          width=\"0.09839357429718876\" height=\"0.4797687861271676\" caption=\"Page Up\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.2168674698795181\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"0.0\""
"          backPlate=\"7\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"GPLC_UP\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\""
"          widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\""
"          setDefaultDoubleClickResetValue=\"0.0\" globalAssignedParameterNumber=\"-1\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\" btnRadioGroupIndex=\"0\""
"          btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.4036144578313253\" y=\"0.1502890173410405\""
"          width=\"0.1606425702811245\" height=\"0.208092485549133\" caption=\"Lyrics/Chords\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"1\" overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.25\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"1.0\""
"          backPlate=\"10\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"808080\""
"          outlineRound=\"4\" outlineThick=\"2\" fontSize=\"15.0\" textPos=\"36\""
"          usesDimming=\"1.0\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.1134831460674157\" y=\"0.1483870967741935\""
"          width=\"0.1910112359550562\" height=\"0.2064516129032258\" caption=\"Main Window\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"1\" overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.2777777777777778\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"1.0\""
"          backPlate=\"10\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"808080\""
"          outlineRound=\"4\" outlineThick=\"2\" fontSize=\"15.0\" textPos=\"36\""
"          usesDimming=\"1.0\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"2\" style=\"1\" x=\"0.2339357429718875\" y=\"0.4884393063583815\""
"          width=\"0.1244979919678715\" height=\"0.9653179190751445\" caption=\"Song List Scroll\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.125748502994012\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"15474\" rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"0.0\""
"          backPlate=\"11\" backPlateVisible=\"0\" invertMIDI=\"0\" displayRange=\"2\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"GPLC_SONG_SCROLL\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\""
"          widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\""
"          setDefaultDoubleClickResetValue=\"0.0\" globalAssignedParameterNumber=\"-1\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.107429718875502\" y=\"0.6502890173410405\""
"          width=\"0.1004016064257028\" height=\"0.5144508670520231\" caption=\"Open/Close\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3707865168539326\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"0.0\""
"          backPlate=\"11\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"GPLC_OPEN\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\""
"          widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\""
"          setDefaultDoubleClickResetValue=\"0.0\" globalAssignedParameterNumber=\"-1\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\" btnRadioGroupIndex=\"0\""
"          btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"5\" style=\"0\" x=\"0.3017068273092369\" y=\"0.4942196531791908\""
"          width=\"0.01305220883534136\" height=\"0.9653179190751445\" caption=\"\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.08021390374331551\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"1.0\""
"          backPlate=\"10\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3a3a3a\" outlineColor=\"f5f5f5\""
"          outlineRound=\"5\" outlineThick=\"10\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"5\" style=\"0\" x=\"0.589859437751004\" y=\"0.4942196531791908\""
"          width=\"0.01305220883534136\" height=\"0.9653179190751445\" caption=\"\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.08021390374331551\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"1.0\""
"          backPlate=\"10\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3a3a3a\" outlineColor=\"f5f5f5\""
"          outlineRound=\"5\" outlineThick=\"10\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.7751004016064257\" y=\"0.5057803468208093\""
"          width=\"0.3433734939759036\" height=\"0.8728323699421965\" caption=\"Note: This panel must be in the global rackspace\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"1\""
"          widgetIgnoresMouse=\"1\" overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.0728476821192053\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"1.0\""
"          backPlate=\"10\" backPlateVisible=\"0\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" fontSize=\"26.0\" textPos=\"33\""
"          usesDimming=\"1.0\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"26\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"</RACKUNIT>"
};