// Rackspace and song selector extension for Gig Performer by @rank13

#include <vector>
#include <string>

// List of panels: the names that appear in the GP UI
std::vector<std::string> panelNames = {"Global Panel"};

// XML for the default included panels
std::vector<std::string> panelXML = { 
"<RACKUNIT size=\"10\" style=\"0\" color=\"ff4682b4\" ver=\"4.199999809265137\">"
"  <WIDGET type=\"2\" style=\"1\" x=\"0.6825396825396826\" y=\"0.4914285714285714\""
"          width=\"0.08531746031746032\" height=\"0.9714285714285714\" caption=\"Page Scroll\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.1294117647058824\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"15474\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"2\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GP_SELECTOR_CP_SCROLL\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\">"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.5882936507936508\" y=\"0.6285714285714286\""
"          width=\"0.07341269841269842\" height=\"0.48\" caption=\"Page Down\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.2173913043478261\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"7\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GP_SELECTOR_CP_DOWN\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\">"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.5158730158730159\" y=\"0.6285714285714286\""
"          width=\"0.07341269841269842\" height=\"0.48\" caption=\"Page Up\" captionIncludesAttribute=\"0\""
"          hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.2173913043478261\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" widgetValue=\"0.0\" backPlate=\"7\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GP_SELECTOR_CP_UP\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\">"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.5502008032128514\" y=\"0.1502890173410405\""
"          width=\"0.1606425702811245\" height=\"0.208092485549133\" caption=\"Lyrics/Chords\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.25\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" widgetValue=\"1.0\" backPlate=\"10\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"808080\""
"          outlineRound=\"4\" outlineThick=\"2\" fontSize=\"15.0\" textPos=\"36\""
"          textColor=\"ffffffff\" usesDimming=\"1.0\">"
"  </WIDGET>"
"  <WIDGET type=\"5\" style=\"0\" x=\"0.4443946188340807\" y=\"0.4973958333333333\""
"          width=\"0.01345291479820628\" height=\"0.9739583333333334\" caption=\"\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.08021390374331551\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"1.0\" backPlate=\"10\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3a3a3a\" outlineColor=\"f5f5f5\""
"          outlineRound=\"5\" outlineThick=\"10\">"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.1134831460674157\" y=\"0.1483870967741935\""
"          width=\"0.1910112359550562\" height=\"0.2064516129032258\" caption=\"Main Window\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.2777777777777778\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"1.0\" backPlate=\"10\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"808080\""
"          outlineRound=\"4\" outlineThick=\"2\" fontSize=\"15.0\" textPos=\"36\""
"          textColor=\"ffffffff\" usesDimming=\"1.0\">"
"  </WIDGET>"
"  <WIDGET type=\"2\" style=\"1\" x=\"0.247191011235955\" y=\"0.4903225806451613\""
"          width=\"0.0853932584269663\" height=\"0.967741935483871\" caption=\"List Scroll\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.1301775147928994\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"15474\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"2\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GP_SELECTOR_SCROLL\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\">"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.1073033707865169\" y=\"0.6193548387096774\""
"          width=\"0.1\" height=\"0.5161290322580645\" caption=\"Open/Close\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"274692468\""
"          rigId=\"6138990167274295412\" widgetValue=\"0.0\" backPlate=\"11\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GP_SELECTOR\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"  </WIDGET>"
"  <WIDGET type=\"5\" style=\"0\" x=\"0.3017068273092369\" y=\"0.4942196531791908\""
"          width=\"0.01305220883534136\" height=\"0.9653179190751445\" caption=\"\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.08021390374331551\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"1.0\" backPlate=\"10\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3a3a3a\" outlineColor=\"f5f5f5\""
"          outlineRound=\"5\" outlineThick=\"10\">"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.3714859437751004\" y=\"0.1502890173410405\""
"          width=\"0.0963855421686747\" height=\"0.208092485549133\" caption=\"HUD\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.3125\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" widgetValue=\"1.0\" backPlate=\"10\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"808080\""
"          outlineRound=\"4\" outlineThick=\"2\" fontSize=\"15.0\" textPos=\"36\""
"          textColor=\"ffffffff\" usesDimming=\"1.0\">"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.3724719101123595\" y=\"0.6258064516129033\""
"          width=\"0.07303370786516854\" height=\"0.4774193548387097\" caption=\"Open\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.2173913043478261\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"7\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"GP_SELECTOR_HUD\""
"          enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\">"
"  </WIDGET>"
"  <WIDGET type=\"5\" style=\"0\" x=\"0.7505020080321285\" y=\"0.4942196531791908\""
"          width=\"0.01305220883534136\" height=\"0.9653179190751445\" caption=\"\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.08021390374331551\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"1.0\" backPlate=\"10\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3a3a3a\" outlineColor=\"f5f5f5\""
"          outlineRound=\"5\" outlineThick=\"10\">"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.8747191011235955\" y=\"0.5064516129032258\""
"          width=\"0.2213483146067416\" height=\"0.8709677419354839\" caption=\"Note: This panel must be in the global rackspace\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"1\""
"          overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.07407407407407407\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"1.0\" backPlate=\"10\" backPlateVisible=\"0\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" fontSize=\"26.0\" textPos=\"33\""
"          textColor=\"ffffffff\" usesDimming=\"1.0\">"
"  </WIDGET>"
"</RACKUNIT>"
};